/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.kiwoomapi.autotrader;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertEquals("Hello from Backend!", classUnderTest.hello(), "app should return 'Hello from Backend!'");
    }
}
