/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.kiwoomapi.autotrader;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    // No tests for App class after refactoring
}
